CREATE OR REPLACE TRIGGER AUDIT_EMPLOYEES_TRG
AFTER INSERT OR UPDATE OR DELETE ON EMPLOYEES
FOR EACH ROW
DECLARE
    v_action VARCHAR2(10);
BEGIN
    IF INSERTING THEN
        v_action := 'INSERT';
        INSERT INTO EMPLOYEES_AUDIT (EMP_ID, COLUMN_NAME, OLD_VALUE, NEW_VALUE, ACTION_TYPE)
        VALUES (:NEW.EMP_ID, 'ALL', NULL,
                'First Name=' || :NEW.FIRST_NAME || ', Last Name=' || :NEW.LAST_NAME || ', Salary=' || :NEW.SALARY,
                v_action);

    ELSIF DELETING THEN
        v_action := 'DELETE';
        INSERT INTO EMPLOYEES_AUDIT (EMP_ID, COLUMN_NAME, OLD_VALUE, NEW_VALUE, ACTION_TYPE)
        VALUES (:OLD.EMP_ID, 'ALL',
                'First Name=' || :OLD.FIRST_NAME || ', Last Name=' || :OLD.LAST_NAME || ', Salary=' || :OLD.SALARY,
                NULL, v_action);

    ELSIF UPDATING THEN
        v_action := 'UPDATE';

        IF :OLD.FIRST_NAME != :NEW.FIRST_NAME THEN
            INSERT INTO EMPLOYEES_AUDIT (EMP_ID, COLUMN_NAME, OLD_VALUE, NEW_VALUE, ACTION_TYPE)
            VALUES (:NEW.EMP_ID, 'FIRST_NAME', :OLD.FIRST_NAME, :NEW.FIRST_NAME, v_action);
        END IF;

        IF :OLD.LAST_NAME != :NEW.LAST_NAME THEN
            INSERT INTO EMPLOYEES_AUDIT (EMP_ID, COLUMN_NAME, OLD_VALUE, NEW_VALUE, ACTION_TYPE)
            VALUES (:NEW.EMP_ID, 'LAST_NAME', :OLD.LAST_NAME, :NEW.LAST_NAME, v_action);
        END IF;

        IF :OLD.SALARY != :NEW.SALARY THEN
            INSERT INTO EMPLOYEES_AUDIT (EMP_ID, COLUMN_NAME, OLD_VALUE, NEW_VALUE, ACTION_TYPE)
            VALUES (:NEW.EMP_ID, 'SALARY', TO_CHAR(:OLD.SALARY), TO_CHAR(:NEW.SALARY), v_action);
        END IF;
    END IF;
END;