INSERT INTO EMAIL_TEMPLATES (NAME, SUBJECT, BODY) 
VALUES ('WELCOME', 'WELCOME TO OUR SERVICE!', '<H1>HELLO!</H1><P>THANK YOU FOR JOINING US.</P>');
COMMIT;

INSERT INTO EMAIL_STATUS (STATUS_CODE, DESCRIPTION, IS_ACTIVE, SORT_ORDER) VALUES 
('PENDING', 'Email waiting to be sent', 'Y', 1);
INSERT INTO EMAIL_STATUS (STATUS_CODE, DESCRIPTION, IS_ACTIVE, SORT_ORDER) VALUES 
('SENDING', 'Email in progress of being sent', 'Y', 2);
INSERT INTO EMAIL_STATUS (STATUS_CODE, DESCRIPTION, IS_ACTIVE, SORT_ORDER) VALUES 
('SENT', 'Email has been sent', 'Y', 3);
INSERT INTO EMAIL_STATUS (STATUS_CODE, DESCRIPTION, IS_ACTIVE, SORT_ORDER) VALUES 
('FAILED', 'Email sending failed', 'Y', 4);
INSERT INTO EMAIL_STATUS (STATUS_CODE, DESCRIPTION, IS_ACTIVE, SORT_ORDER) VALUES 
('RETRY', 'Email in queue for retry attempt', 'Y', 5);
COMMIT;

INSERT INTO EMAIL_PRIORITY (PRIORITY_LEVEL, NAME, DESCRIPTION, COLOR_CODE, RESPONSE_TIME_HOURS) VALUES 
(1, 'High', 'Highest priority - requires immediate attention', 'RED', 1);
INSERT INTO EMAIL_PRIORITY (PRIORITY_LEVEL, NAME, DESCRIPTION, COLOR_CODE, RESPONSE_TIME_HOURS) VALUES 
(2, 'Medium', 'Standard priority - normal processing', 'YELLOW', 4);
INSERT INTO EMAIL_PRIORITY (PRIORITY_LEVEL, NAME, DESCRIPTION, COLOR_CODE, RESPONSE_TIME_HOURS) VALUES 
(3, 'Low', 'Low priority - processing when system is less busy', 'GREEN', 24);

COMMIT;