CREATE TABLE EMAIL_TEMPLATES (
    ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME        VARCHAR2(100) NOT NULL UNIQUE,  
    SUBJECT     VARCHAR2(500) NOT NULL,         
    BODY        CLOB NOT NULL,                  
    CREATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP
);
