CREATE TABLE EMAIL_PRIORITY (
    PRIORITY_LEVEL NUMBER PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL,
    DESCRIPTION VARCHAR2(200) NOT NULL,
    COLOR_CODE VARCHAR2(20),
    RESPONSE_TIME_HOURS NUMBER
);