CREATE TABLE EMAIL_STATUS (
    STATUS_CODE VARCHAR2(20) PRIMARY KEY,
    DESCRIPTION VARCHAR2(200) NOT NULL,
    IS_ACTIVE VARCHAR2(1) DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y', 'N')),
    SORT_ORDER NUMBER NOT NULL
);
