CREATE OR REPLACE PACKAGE EMAIL_PKG AS
    PROCEDURE ADD_EMAIL(P_RECIPIENT VARCHAR2, P_SUBJECT VARCHAR2, P_TEMPLATE_ID NUMBER);
    PROCEDURE UPDATE_EMAIL_STATUS(P_EMAIL_ID NUMBER, P_STATUS VARCHAR2, P_ERROR_MSG VARCHAR2 DEFAULT NULL);
    PROCEDURE UPDATE_TEMPLATE(P_TEMPLATE_ID NUMBER, P_NEW_BODY CLOB, P_MODIFIED_BY VARCHAR2);
	PROCEDURE ADD_EMAIL_TEMPLATE(P_TEMPLATE_NAME VARCHAR2, P_TEMPLATE_SUBJECT VARCHAR2, P_TEMPLATE_BODY CLOB);
END EMAIL_PKG;
/
