CREATE TABLE EMAIL_TEMPLATES_AUDIT (
    ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TEMPLATE_ID   NUMBER NOT NULL,
    OLD_BODY      CLOB,
    NEW_BODY      CLOB,
    MODIFIED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP,
    MODIFIED_BY   VARCHAR2(100),
    CONSTRAINT FK_EMAIL_TEMPLATE_AUDIT FOREIGN KEY (TEMPLATE_ID) REFERENCES EMAIL_TEMPLATES(ID)
);
