CREATE TABLE EMAIL_READY_TO_SEND (
    ID          NUMBER GENERATED ALWAYS AS IDENTITY,
    RECIPIENT   VARCHAR2(1000) NOT NULL,  
    SUBJECT     VARCHAR2(500) NOT NULL,  
    TEMPLATE_ID NUMBER NOT NULL,        
    BODY        CLOB NOT NULL,  
    CREATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_EMAIL_READY_TO_SEND PRIMARY KEY (ID, CREATED_AT),
    CONSTRAINT FK_READY_TEMPLATE FOREIGN KEY (TEMPLATE_ID) REFERENCES EMAIL_TEMPLATES(ID)
)
PARTITION BY RANGE (CREATED_AT) (
    PARTITION ERTS_202301 VALUES LESS THAN (TO_DATE('2025-03-01', 'YYYY-MM-DD')),
    PARTITION ERTS_202302 VALUES LESS THAN (TO_DATE('2025-04-01', 'YYYY-MM-DD'))
    PARTITION ERTS_FUTURE VALUES LESS THAN (MAXVALUE)
);

CREATE INDEX IDX_ERTS_LOCAL_TEMPLATE_ID ON EMAIL_READY_TO_SEND(TEMPLATE_ID) LOCAL;
CREATE INDEX IDX_ERTS_LOCAL_RECIPIENT ON EMAIL_READY_TO_SEND(RECIPIENT) LOCAL;