CREATE TABLE EMAIL_QUEUE (
    ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EMAIL_ID      NUMBER NOT NULL,
	CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP,
    STATUS        VARCHAR2(20) DEFAULT 'PENDING',
    PRIORITY      NUMBER DEFAULT 1, 
    ATTEMPT_COUNT NUMBER DEFAULT 0,
    LAST_ATTEMPT  TIMESTAMP NULL,
	NEXT_ATTEMPT  TIMESTAMP NULL,
    SENT_AT       TIMESTAMP NULL,
    ERROR_MSG     VARCHAR2(1000) NULL,
    CONSTRAINT FK_EMAIL_QUEUE_READY FOREIGN KEY (EMAIL_ID) REFERENCES EMAIL_READY_TO_SEND(ID),
    CONSTRAINT FK_EMAIL_QUEUE_STATUS FOREIGN KEY (STATUS) REFERENCES EMAIL_STATUS(STATUS_CODE),
    CONSTRAINT FK_EMAIL_QUEUE_PRIORITY FOREIGN KEY (PRIORITY) REFERENCES EMAIL_PRIORITY(PRIORITY
);

CREATE INDEX IDX_EQ_STATUS ON EMAIL_QUEUE(STATUS);
CREATE INDEX IDX_EQ_PRIORITY ON EMAIL_QUEUE(PRIORITY);
CREATE INDEX IDX_EQ_CREATED_AT ON EMAIL_QUEUE(CREATED_AT);