CREATE OR REPLACE VIEW V_EMAIL_QUEUE_STATUS AS
SELECT 
    EQ.ID,
    ER.RECIPIENT,
    ER.SUBJECT,
    ES.STATUS_CODE AS STATUS,
    ES.DESCRIPTION AS STATUS_DESC,
    EP.PRIORITY_LEVEL AS PRIORITY,
    EP.NAME AS PRIORITY_NAME,
    EQ.CREATED_AT,
    EQ.LAST_ATTEMPT,
    EQ.SENT_AT
FROM 
    EMAIL_QUEUE EQ
JOIN 
    EMAIL_READY_TO_SEND ER ON EQ.EMAIL_ID = ER.ID
JOIN 
    EMAIL_STATUS ES ON EQ.STATUS = ES.STATUS_CODE
LEFT JOIN 
    EMAIL_PRIORITY EP ON EQ.PRIORITY = EP.PRIORITY_LEVEL;