CREATE OR REPLACE VIEW V_NON_COMPLIANT_ACCOUNTS AS
SELECT 
    U.EMAIL AS RECIPIENT,
    U.FULL_NAME AS NAME,
    COUNT(A.ID) AS NON_COMPLIANT_COUNT,
    MAX(A.FIX_DEADLINE) AS DEADLINE
FROM USERS U
JOIN ACCOUNTS A ON U.ID = A.USER_ID
WHERE A.COMPLIANCE_STATUS = 'NON_COMPLIANT'
GROUP BY U.EMAIL, U.FULL_NAME;