CREATE OR REPLACE VIEW V_PENDING_EMAILS AS
SELECT 
    EQ.ID AS QUEUE_ID,
    ER.RECIPIENT,
    ER.SUBJECT,
    ET.BODY AS TEMPLATE_BODY,
    ER.BODY AS FINAL_BODY,
    EQ.STATUS,
    EQ.CREATED_AT,
    EQ.SENT_AT,
    EQ.ERROR_MSG
FROM EMAIL_QUEUE EQ
JOIN EMAIL_READY_TO_SEND ER ON EQ.EMAIL_ID = ER.ID
JOIN EMAIL_TEMPLATES ET ON ER.TEMPLATE_ID = ET.ID
WHERE EQ.STATUS = 'PENDING';