CREATE TABLE jobs (
    job_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_name       VARCHAR2(128) NOT NULL,
    job_code       VARCHAR2(4000) NOT NULL,
    created_by     VARCHAR2(128) NOT NULL,
    modified_by    VARCHAR2(128),
    created_date   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_date  TIMESTAMP,
    is_active      CHAR(1) DEFAULT 'Y' CHECK (is_active IN ('Y', 'N')),
    freq           VARCHAR2(20) NOT NULL,
    byhour         NUMBER NOT NULL,
    byminute       NUMBER NOT NULL,
    bysecond       NUMBER NOT NULL
);
