CREATE TABLE job_logs (
    log_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id            NUMBER NOT NULL,
    log_date          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    execution_status  VARCHAR2(20),
    error_message     VARCHAR2(4000),
    run_duration      INTERVAL DAY TO SECOND,
    FOREIGN KEY (job_id) REFERENCES jobs(job_id)
);
