CREATE TABLE job_audit (
    audit_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id       NUMBER NOT NULL,
    old_job_code VARCHAR2(4000),
    new_job_code VARCHAR2(4000),
    modified_by  VARCHAR2(128) NOT NULL,
    modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    old_freq     VARCHAR2(20),
    new_freq     VARCHAR2(20),
    old_byhour   NUMBER,
    new_byhour   NUMBER,
    old_byminute NUMBER,
    new_byminute NUMBER,
    old_bysecond NUMBER,
    new_bysecond NUMBER,
    FOREIGN KEY (job_id) REFERENCES jobs(job_id)
);
